### ISSUE TITLE
Long messages or messages with new line char print on every line for each frame

### ISSUE THREAD

**Issue by cchaffatt** [pavdmyt/yaspin#131]
Thanks for this fun lib. I noticed messages will be repeated if any of the below triggers are encountered.

[notes]
version = 1.5.0
machine = mac (catalina)

[triggers]
* very long message (longer than buffer width ie resized window)
* messages with '\n' (new line character)

[screenshot]
<img width="975" alt="Screen Shot 2021-05-11 at 6 42 14 PM" src="https://user-images.githubusercontent.com/2129902/117893898-48687100-b289-11eb-9097-8af151320fda.png">

**Comment by pavdmyt** [comment]
Hi @cchaffatt 

The behavior triggered by `\n` symbol is kind of expected. Yaspin tries to avoid interfering with user input, otherwise handling all possible [terminal escape sequences](https://docstore.mik.ua/orelly/unix/upt/ch05_08.htm) would make code much more complicated. It is expected that yaspin receives sanitized text.

The case with long messages is interesting, I'll investigate that.

Thanks for reporting this!

**Comment by pavdmyt** [comment]
Fixed by https://github.com/pavdmyt/yaspin/pull/240
