### ISSUE TITLE
Allow write() to print non-string objects

### ISSUE THREAD

**Issue by sebageek** [pavdmyt/yaspin#34]
As I have to use `write()` in a yaspin context instead of `print()` I tend to use it in a similar way. This often includes printing non-string objects. `print()` calls `repr()` automatically on anything that is not a string, whereas yaspin runs into an assertion.

Would you be open to replace that assertion with something just calling `repr()` on the given text? This coud also be implemented for the spinner text itself. I'd also volunteer to bring up a PR for this.

**Comment by pavdmyt** [comment]
@sebageek feel free to open the PR.

**Comment by sebageek** [comment]
As #37 was rejected are there still ambitions to implement this feature? If the problem is that #37 was implementing too much of the `print()` logic (i.e. the multiple arguments) I can implement this by just calling `str()` on the one argument we get. If not this bug can probably just be closed.

**Comment by pavdmyt** [comment]
It seems that I don't completely understand the issue. Let's try to sort out the details.

> `print()` calls `repr()` automatically on anything that is not a string, whereas yaspin runs into an assertion

I agree that calling `repr` on non-string objects makes sense for `write` method. #37 was focused on implementing `*args` logic and missed `repr` for non-string objects. I declined it mostly because of composing strings from `*args` which I think should be better handled outside of yaspin.

I'm still open for PR which allows to use non-string objects as arguments to `write`.

**Comment by pavdmyt** [comment]
Included in [yaspin v1.4.0](https://github.com/pavdmyt/yaspin/releases/tag/v1.4.0)
