### ISSUE TITLE
Yaspin thread in daemon mode

### ISSUE THREAD

**Issue by brupelo** [pavdmyt/yaspin#43]
Is there any good reason for not allowing yaspin to be spawned in daemon mode? 

Why am I asking? Because if not you can't interrupt the process execution using `Ctrl+C`.

Thx.

Ns. Pretty amazing library I must say... sadly I can't see colored emojis using conemu on win7 :'(

**Comment by pavdmyt** [comment]
Hi,

Actually yaspin supports handling signals which allows to manage `Ctrl+C` particularly: https://github.com/pavdmyt/yaspin#handling-posix-signals

Here some more examples for signal handling: https://github.com/pavdmyt/yaspin/blob/master/examples/signals.py

**Comment by brupelo** [comment]
Oh, I see... that's actually quite cool rather than spawn in `daemon` thread.... Ok, I'll try to confirm that solution works properly (then I'll just guess I'll close if this one doesn't apply). 

Reason why I'd opened this issue was mainly because `Ctrl+c` wasn't working properly on windows+conemu so i had to switch to daemon mode.

Thanks.

**Comment by pavdmyt** [comment]
Closing for now. Feel free to reopen.

**Comment by intradeus** [comment]
If people are looking at this thread for a way to stop spinners from spinning, on Windows, even after a KeyboardInterrupt has been caught, the solution is rather easy : Make sure to kill the whole process after catching your keyboard with 
`os.kill(os.getpid(), signal.SIGINT)`

Ex: 
```python
import os, signal, yaspin

def  main():
try:
  spinner = yaspin(text=colored(message, self.text_color), spinner=loading_spinner, color=self.spinner_color, side="right")
  yaspin.start()
  # ..... do something
  yaspin.stop()
except KeyboardInterrupt:
  print("Aborder by user")
  os.kill(os.getpid(), signal.SIGINT) # This will stop everything from the current process, spinners included
  sys.exit(0)
```

I tried to create my own signal handlers, etc. but couldn't make it work (had the error `'module' object has no attribute 'SIGKILL'`, because SIGKILL doesn't exist in Windows)
